[package]
name = "huaci-ai"
version = "1.0.7"
description = "轻量级划词翻译工具"
authors = ["huaci-ai"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = ["tray-icon", "image-ico"] }
tauri-plugin-clipboard-manager = "2.0"
tauri-plugin-shell = "2.0"
tauri-plugin-global-shortcut = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1"
dirs = "5"

alloc-no-stdlib = { version = "=2.0.4", default-features = false }
alloc-stdlib = { version = "=0.2.2", default-features = false }
brotli-decompressor = { version = "=5.0.1", default-features = false }

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Accessibility",
    "Win32_System_DataExchange",
    "Win32_System_Com",
]

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
